### ISSUE TITLE
Update to 1.16?

### ISSUE THREAD

**Issue by NebelNidas** [ExtraCrafTX/ChestLatchFixer#1]
Just wanted to ask, since this visual glitch is really annoying... 😂

**Comment by ExtraCrafTX** [comment]
It should work as-is with 1.16, and in my testing it does.
Please open another issue with more details in case it doesn't work for you. Thanks.

**Comment by NebelNidas** [comment]
You're right, it works perfectly now... Must have been a mod incompatibility back when I created this issue. 🤔
